### ISSUE TITLE
插件开发调试问题

### ISSUE THREAD

**Issue by retisan** [zhixiaoqiang/yapi2code#12]
按照大佬的说明启动项目后，更改src/core/index.ts的代码触发了重新编译，但是即使reload webview后也不是更改后的代码，只能关闭扩展编辑器，重新点击源代码编辑器的run and debug启动一个新的扩展编辑器才能看到应用最新代码后的扩展，请问老大， 我如何才能在改动代码后直接看到代码变动后的扩展，类似于hmr？期待得到老哥的回复

**Comment by zhixiaoqiang** [comment]
> 按照大佬的说明启动项目后，更改src/core/index.ts的代码触发了重新编译，但是即使reload webview后也不是更改后的代码，只能关闭扩展编辑器，重新点击源代码编辑器的run and debug启动一个新的扩展编辑器才能看到应用最新代码后的扩展，请问老大， 我如何才能在改动代码后直接看到代码变动后的扩展，类似于hmr？期待得到老哥的回复

最近实在业务繁忙，我得周末才能看看了😢
 hmr 的话因为 ws 通信协议跟 rspack的不一致所以不能直接实现，知乎上有一篇 webpack 相关的，你可以试试提 MR 🤠

**Comment by zhixiaoqiang** [comment]
应该是修正了，你再试试，修改了调试脚本
