### ISSUE TITLE
接口能暴露公网吗

### ISSUE THREAD

**Issue by MrZmcH** [zhixiaoqiang/yapi2code#3]
http://yapi.internal.weimob.com/

**Comment by zhixiaoqiang** [comment]
> [http://yapi.internal.weimob.com](http://yapi.internal.weimob.com/)

这个地址只需要换成你们内部使用的地址就行，等于是适用所有内外网

**Comment by MrZmcH** [comment]
那接口返回数据能给下吗，因为我实际是学习下vscode插件开发，这个yapi我不太清楚是啥😂

**Comment by zhixiaoqiang** [comment]
> 那接口返回数据能给下吗，因为我实际是学习下vscode插件开发，这个yapi我不太清楚是啥😂

github：https://github.com/YMFE/yapi

site：http://yapi.smart-xwork.cn (服务器地址配置这个即可)

你可以登录后尝试下

**Comment by MrZmcH** [comment]
> 

非常感谢

**Comment by MrZmcH** [comment]
@zhixiaoqiang 最近的更新好像导致调试无法正常进行Lost connection to debugee，原来是可以的

**Comment by zhixiaoqiang** [comment]
> @zhixiaoqiang 最近的更新好像导致调试无法正常进行Lost connection to debugee，原来是可以的

测试了下可以诶
