### ISSUE TITLE
登录失败，是不支持ip端口的链接吗？

### ISSUE THREAD

**Issue by kecikeci** [zhixiaoqiang/yapi2code#4]
![image](https://user-images.githubusercontent.com/32811349/215313606-752d95bc-6917-4afb-a2b4-45854dec4925.png)

**Comment by kecikeci** [comment]
已确认账号密码没问题，可以正常登录。这个插件登录不了

**Comment by zhixiaoqiang** [comment]
> 已确认账号密码没问题，可以正常登录。这个插件登录不了

浏览器可以正常浏览ip地址是吗，我这边试了下访问不通

**Comment by kecikeci** [comment]
> > 已确认账号密码没问题，可以正常登录。这个插件登录不了
> 
> 浏览器可以正常浏览ip地址是吗，我这边试了下访问不通

![image](https://user-images.githubusercontent.com/32811349/215315027-0f60d2de-b8ac-4ec8-9215-966651b10bd2.png)

浏览器可以访问的，你试的哪个？

**Comment by zhixiaoqiang** [comment]
> > > 已确认账号密码没问题，可以正常登录。这个插件登录不了
> > 
> > 
> > 浏览器可以正常浏览ip地址是吗，我这边试了下访问不通
> 
> ![image](https://user-images.githubusercontent.com/32811349/215315027-0f60d2de-b8ac-4ec8-9215-966651b10bd2.png)
> 
> 浏览器可以访问的，你试的哪个？

ping 了下内网的 ip 最终访问不了，应该是只是 ping 到了网关层，没到实际的服务器

**Comment by kecikeci** [comment]
> ping 了下内网的 ip 最终访问不了，应该是只是 ping 到了网关层，没到实际的服务器

那就是不支持ip访问？可以解决下吗

**Comment by zhixiaoqiang** [comment]
> 

代码里没做限制，你可以 clone 后调试下看看吗，欢迎 PR~

**Comment by zhixiaoqiang** [comment]
> > ping 了下内网的 ip 最终访问不了，应该是只是 ping 到了网关层，没到实际的服务器
> 
> 那就是不支持ip访问？可以解决下吗

代码里没做限制，你可以 clone 后调试下看看吗，欢迎 PR~

**Comment by kecikeci** [comment]
> 代码里没做限制，你可以 clone 后调试下看看吗，欢迎 PR~

我是做后端的，才在学着写前端，能力有限。。。心有余而力不足

**Comment by zhixiaoqiang** [comment]
> 

那我先看看，目前没有能复现的条件还挺麻烦的😔

**Comment by zhixiaoqiang** [comment]
> > 代码里没做限制，你可以 clone 后调试下看看吗，欢迎 PR~
> 
> 我是做后端的，才在学着写前端，能力有限。。。心有余而力不足


那我先看看，目前没有能复现的条件还挺麻烦的😔

**Comment by kecikeci** [comment]
> 那我先看看，目前没有能复现的条件还挺麻烦的😔

![image](https://user-images.githubusercontent.com/32811349/215315528-bbd356b5-ecad-4080-939c-5128046047ad.png)

确认是ip不支持，我解析了个域名，可以登录成功了

**Comment by kecikeci** [comment]
如有需要，可以联系我提供环境支持，qq 641034445

**Comment by kecikeci** [comment]
![image](https://user-images.githubusercontent.com/32811349/215315993-35cbb4e1-a93c-47e9-9415-98b7acb05a72.png)

不好意思搞错了，换了域名也不行。。。有可能是我yapi版本问题
我弄得docker搭建的
https://github.com/YMFE/yapi/blob/master/CHANGELOG.md

**Comment by zhixiaoqiang** [comment]
> ![image](https://user-images.githubusercontent.com/32811349/215315993-35cbb4e1-a93c-47e9-9415-98b7acb05a72.png)
> 
> 不好意思搞错了，换了域名也不行。。。有可能是我yapi版本问题 我弄得docker搭建的 [YMFE/yapi@`master`/CHANGELOG.md](https://github.com/YMFE/yapi/blob/master/CHANGELOG.md?rgh-link-date=2023-01-29T09%3A01%3A30Z)

端口去掉正常吗，已经有域名了就不需要端口了

**Comment by zhixiaoqiang** [comment]
> 

使用的最新版吗，最新版 0.0.10

**Comment by kecikeci** [comment]
> > 
> 
> 使用的最新版吗，最新版 0.0.10

是的
![image](https://user-images.githubusercontent.com/32811349/215317136-c1a343a5-4d30-434a-a614-6841f3147089.png)


我去反代下，试下域名

**Comment by kecikeci** [comment]
> > 
> 
> 使用的最新版吗，最新版 0.0.10

![image](https://user-images.githubusercontent.com/32811349/215317622-cd9eef72-8f04-44cc-afc9-8678ce3eaa0d.png)
![image](https://user-images.githubusercontent.com/32811349/215317702-f2fbf563-a6dc-4818-b8a1-e38d22462232.png)

域名也不行，可能就是我的yapi的问题

**Comment by zhixiaoqiang** [comment]
> 

这个错误："options.url ^ options.socketpath (string) required" 是 ldap 报的，可以查下看看

**Comment by kecikeci** [comment]
> > 
> 
> 这个错误："options.url ^ options.socketpath (string) required" 是 ldap 报的，可以查下看看

![image](https://user-images.githubusercontent.com/32811349/215317953-40a62335-f03f-472a-96d0-53e4a4f25733.png)

开发者模式下，日志是登录成功的。。。彻底不会了

**Comment by zhixiaoqiang** [comment]
> > > 
> > 
> > 
> > 这个错误："options.url ^ options.socketpath (string) required" 是 ldap 报的，可以查下看看
> 
> ![image](https://user-images.githubusercontent.com/32811349/215317953-40a62335-f03f-472a-96d0-53e4a4f25733.png)
> 
> 开发者模式下，日志是登录成功的。。。彻底不会了

这个日志有点问题，没判断状态码非 200 的情况，登录不了的问题应该跟跟这个一样 https://github.com/zhixiaoqiang/yapi2code/issues/5

**Comment by kecikeci** [comment]
> 这个日志有点问题，没判断状态码非 200 的情况，登录不了的问题应该跟跟这个一样 #5

好的   感谢大佬~

**Comment by zhixiaoqiang** [comment]
更新为 0.0.11版本后切换登录方式即可，默认 ldap
![image](https://user-images.githubusercontent.com/25545093/215379646-65510a9b-33a2-4b79-ac16-bbd669d0c300.png)

**Comment by kecikeci** [comment]
> 

感谢大佬  期待发版

**Comment by zhixiaoqiang** [comment]
> > 
> 
> 感谢大佬 期待发版

已发好
