### ISSUE TITLE
你好，我用了这个公共的yapi端，试了下也登录不上

### ISSUE THREAD

**Issue by Lingtin** [zhixiaoqiang/yapi2code#5]
https://yapi.pro

大佬给看看~

**Comment by Lingtin** [comment]
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/25638355/215330613-307c158b-e273-487d-9808-63b9d765a425.png">

**Comment by zhixiaoqiang** [comment]
你这边不是用的ldap的，我添加个切换按钮，默认为 ldap

**Comment by Lingtin** [comment]
期待新版本，感谢大佬 ！

**Comment by zhixiaoqiang** [comment]
更新为 0.0.11版本后切换登录方式即可，默认 ldap
![image](https://user-images.githubusercontent.com/25545093/215379646-65510a9b-33a2-4b79-ac16-bbd669d0c300.png)

**Comment by Lingtin** [comment]
感谢大佬，后续能支持模板生成代码就太棒了
