### ISSUE TITLE
Bug：点刷新无效

### ISSUE THREAD

**Issue by kecikeci** [zhixiaoqiang/yapi2code#6]
![image](https://user-images.githubusercontent.com/32811349/215381625-8c6cf894-dccd-4635-820f-8cccbdce7efe.png)

![image](https://user-images.githubusercontent.com/32811349/215381675-bc8ff9d4-731d-4719-9669-cac8461b7e1b.png)

**Comment by kecikeci** [comment]
还发现重新登录该页面也不刷新，还是历史数据，即使换账号登录也不变

**Comment by kecikeci** [comment]
刷新无效应该是缓存了，过了会刷新成功了。但是换域名换账号登录，是没刷新

**Comment by zhixiaoqiang** [comment]
缓存问题我处理下

**Comment by zhixiaoqiang** [comment]
已发布最新版 0.0.13

**Comment by kecikeci** [comment]
nice    可以了

期待模板配置功能
