### ISSUE TITLE
Bug：部分接口生成异常

### ISSUE THREAD

**Issue by kecikeci** [zhixiaoqiang/yapi2code#7]
![image](https://user-images.githubusercontent.com/32811349/215383385-286a8c7c-7d21-4a1c-a024-c744d6c7aa52.png)

![image](https://user-images.githubusercontent.com/32811349/215383424-38103d69-96a3-4045-b9db-d31ed303e03a.png)

我的新增和修改的全都生成失败了，只有查询的接口成功了

**Comment by kecikeci** [comment]
https://yapi.pro/

账号 ceo@kecikeci.com
密码 123456

**Comment by zhixiaoqiang** [comment]
类型 为 object 但是没内容导致报错了，我这边兼容下，没内容就返回 {}

**Comment by kecikeci** [comment]
> 类型 为 object 但是没内容导致报错了，我这边兼容下，没内容就返回 {}

感谢大佬，可以生成了
