### ISSUE TITLE
生成的文件能否支持模板配置

### ISSUE THREAD

**Issue by kecikeci** [zhixiaoqiang/yapi2code#8]
类似于vscode-yapi插件的模板

![image](https://user-images.githubusercontent.com/32811349/215406646-3bbc372e-d777-48fd-8783-ca91407e444c.png)

**Comment by zhixiaoqiang** [comment]
计划中，但是稍微滞后一些

**Comment by kecikeci** [comment]
> 计划中，但是稍微滞后一些

大佬666，这个插件肯定能火

**Comment by zhixiaoqiang** [comment]
已发布最新版，实验性的支持自定义部分内容，后续将会支持更多的自定义内容

**Comment by kecikeci** [comment]
很好用，满足需求了。大佬666~
